spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/money_transfer_db}
    username: ${DB_USER:money_user}
    password: ${DB_PASSWORD:money_password}
    driver-class-name: org.postgresql.Driver

  # Disable JPA/Hibernate for now (we haven't added it)
  jpa:
    open-in-view: false

server:
  port: 8080

# Add logging configuration here
logging:
  level:
    root: INFO
    com.example.moneytransferservice: DEBUG
    org.springframework: WARN
    org.springframework.jdbc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: money-transfer-service.log


springdoc:
  api-docs:
    enabled: true  # Keep enabled to support Swagger UI
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml  # Point to your static file
    disable-swagger-default-url: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  show-actuator: false
  # No need for packages-to-scan since we're using a static file
